# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newgen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import requests

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1024, 635)
        font = QtGui.QFont()
        Form.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        Form.setAttribute(QtCore.Qt.WA_TranslucentBackground)

        font.setFamily("MS PGothic")
        Form.setFont(font)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(60, 40, 721, 591))
        self.widget.setStyleSheet("\n"
"")
        self.widget.setObjectName("widget")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(330, 430, 191, 71))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton#pushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0.220075, y1:0.222, x2:0.915423, y2:0.943, stop:0.218905 rgba(181, 143, 214, 255), stop:0.985075 rgba(83, 65, 116, 255));\n"
"\n"
"}\n"
"QPushButton#pushButton:hover{\n"
"border-radius:2px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.283582, y1:0.335, x2:0.950249, y2:0.881, stop:0 rgba(73, 85, 199, 255), stop:0.900498 rgba(178, 179, 255, 255));\n"
"}\n"
"QPushButton#pushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color: qlineargradient(spread:pad, x1:0.264, y1:0.289818, x2:0.965, y2:0.960227, stop:0.218905 rgba(31, 137, 186, 255), stop:0.985075 rgba(187, 29, 255, 255));\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(0, 0, 291, 571))
        self.label.setStyleSheet("border-image: url(:/image/mobilewal.jpg);\n"
"border-top-left-radius: 80px;\n"
"background-color:rgba(0, 0, 0, 80);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(290, 0, 291, 571))
        self.label_3.setStyleSheet("border-bottom-right-radius: 80px;\n"
"background-color: rgb(54, 54, 54);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(370, -10, 121, 91))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setGeometry(QtCore.QRect(300, 180, 271, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit.setFont(font)

        def text():
            webhookurl = self.lineEdit.text()
            message = self.lineEdit_2.text()
            data = {"content": f"{message}"}
            requests.post(webhookurl, data)
            self.lineEdit_2.clear()

        self.pushButton.clicked.connect(text)
        self.lineEdit.setStyleSheet("background-color:rgba(255, 255, 255, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(255, 255, 255, 100);\n"
"padding-bottom:7px;\n"
"color: rgba(231, 231, 231, 50);")
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setGeometry(QtCore.QRect(300, 320, 271, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("background-color:rgba(255, 255, 255, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(255, 255, 255, 100);\n"
"padding-bottom:7px;\n"
"color: rgb(231, 231, 231);")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(290, 0, 291, 71))
        self.label_2.setStyleSheet("border-top-left-radius: 20px;\n"
"border-top-right-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"border-bottom-right-radius: 20px;\n"
"background-color: qlineargradient(spread:pad, x1:0.0103483, y1:0, x2:0.995, y2:0.994318, stop:0.218905 rgba(13, 50, 77, 255), stop:0.985075 rgba(127, 90, 131, 255));\n"
"\n"
"")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(290, 0, 291, 71))
        self.label_5.setStyleSheet("border-top-left-radius: 20px;\n"
"border-top-right-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"border-bottom-right-radius: 20px;\n"
"background-color: rgb(94, 165, 141);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(0, 0, 291, 571))
        self.label_6.setStyleSheet("border-top-left-radius: 80px;\n"
"background-color: rgba(50, 50, 50, 130);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_5.raise_()
        self.label_3.raise_()
        self.label.raise_()
        self.pushButton.raise_()
        self.lineEdit.raise_()
        self.lineEdit_2.raise_()
        self.label_2.raise_()
        self.label_4.raise_()
        self.label_6.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "FartWareHook"))
        self.pushButton.setText(_translate("Form", "Send"))
        self.label_4.setText(_translate("Form", "FARTWAREHOOK"))
        self.lineEdit.setPlaceholderText(_translate("Form", "Webhook"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "Message"))
import res


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
